[package]
distribution = "2201.8.4"
org = "ballerinax"
name = "docusign.dsclick"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["eSignature", "Cost/Freemium", "Documents", "Collaboration", "Digital Signature"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-docusign.dsclick"

[build-options]
observabilityIncluded = false

[platform.java17]
graalvmCompatible = true
